- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
        
    - name: Test Command
      debug:
        msg: "Hello Hello!"
        
      
